/*
 * TodoApp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package service

import (
	"github.com/gin-gonic/gin"
)

type PomosAPI struct {
}

// Get /api/pomos/active
// Get Active Pomo for User
func (api *PomosAPI) ApiPomosActiveGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /api/pomos/history
// List Finished Pomos
func (api *PomosAPI) ApiPomosHistoryGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /api/pomos/:pomo_id/cancel
// Cancel Pomo
func (api *PomosAPI) ApiPomosPomoIdCancelPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /api/pomos/:pomo_id/complete
// Complete Pomo
func (api *PomosAPI) ApiPomosPomoIdCompletePost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Delete /api/pomos/:pomo_id
// Delete Pomo
func (api *PomosAPI) ApiPomosPomoIdDelete(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /api/pomos/:pomo_id
// Get Pomo by ID
func (api *PomosAPI) ApiPomosPomoIdGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /api/pomos/start
// Start Pomo
func (api *PomosAPI) ApiPomosStartPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}
