/*
 * TodoApp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package service

import (
	"github.com/gin-gonic/gin"
)

type UsersAPI struct {
}

// Delete /api/users/me
// Delete User
func (api *UsersAPI) ApiUsersMeDelete(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /api/users/me
// Get Current User
func (api *UsersAPI) ApiUsersMeGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Put /api/users/me
// Update User
func (api *UsersAPI) ApiUsersMePut(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /api/users
// Register User
func (api *UsersAPI) ApiUsersPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}
