/*
 * TodoApp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package service

import (
	"github.com/gin-gonic/gin"
)

type TodosAPI struct {
}

// Get /api/todos
// List All Todos
func (api *TodosAPI) ApiTodosGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /api/todos
// Create Todo
func (api *TodosAPI) ApiTodosPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Delete /api/todos/:todo_id
// Delete Todo
func (api *TodosAPI) ApiTodosTodoIdDelete(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /api/todos/:todo_id
// Get Todo by ID
func (api *TodosAPI) ApiTodosTodoIdGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Put /api/todos/:todo_id
// Update Todo Title & Desc
func (api *TodosAPI) ApiTodosTodoIdPut(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Put /api/todos/:todo_id/status
// Update Todo Status
func (api *TodosAPI) ApiTodosTodoIdStatusPut(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Delete /api/todos/:todo_id/subtasks
// Remove Subtask from Todo
func (api *TodosAPI) ApiTodosTodoIdSubtasksDelete(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /api/todos/:todo_id/subtasks
// Add Subtask to Todo
func (api *TodosAPI) ApiTodosTodoIdSubtasksPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}
