/*
 * TodoApp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package service

type ApiTodosPost201Response struct {
	Id int32 `json:"id"`

	Title string `json:"title"`

	Description string `json:"description"`

	Status string `json:"status"`

	UserId int32 `json:"user_id"`

	ParentId int32 `json:"parent_id"`

	SubTasks []string `json:"sub_tasks"`

	CreatedAt string `json:"created_at"`
}
