/*
 * TodoApp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package service

type ApiPomosStartPostRequest struct {
	UserId int32 `json:"user_id"`

	Topic string `json:"topic"`

	TodoId int32 `json:"todo_id"`

	IsPositive bool `json:"is_positive"`
}
