/*
 * TodoApp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package service

type ApiUsersPost200Response struct {
	Id int32 `json:"id"`

	Username string `json:"username"`

	Email string `json:"email"`

	IsActive bool `json:"is_active"`

	CreatedAt string `json:"created_at"`
}
