/*
 * TodoApp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package service

type ApiPomosActiveGet200Response struct {
	Id int32 `json:"id"`

	UserId int32 `json:"user_id"`

	Status string `json:"status"`

	StartedAt string `json:"started_at"`

	DurationSeconds int32 `json:"duration_seconds"`

	Topic string `json:"topic"`

	TodoId int32 `json:"todo_id"`

	CreatedAt string `json:"created_at"`
}
