/*
 * TodoApp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package service

type ApiTodosGet200ResponseInner struct {
	Id int32 `json:"id,omitempty"`

	Title string `json:"title,omitempty"`

	Status string `json:"status,omitempty"`

	UserId int32 `json:"user_id,omitempty"`

	CreatedAt string `json:"created_at,omitempty"`
}
