/*
 * TodoApp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package service

type ApiUsersMePutRequest struct {
	Username string `json:"username"`

	Email string `json:"email"`

	PasswordHash string `json:"password_hash"`

	IsActive bool `json:"is_active"`
}
