/*
 * TodoApp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package service

type ApiTodosTodoIdSubtasksPostRequest struct {
	SubtaskId int32 `json:"subtask_id"`
}
