/*
 * TodoApp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package service

type ApiPomosHistoryGet200ResponseInner struct {
	Id int32 `json:"id,omitempty"`

	UserId int32 `json:"user_id,omitempty"`

	Status string `json:"status,omitempty"`

	StartedAt string `json:"started_at,omitempty"`

	EndedAt string `json:"ended_at,omitempty"`

	DurationSeconds int32 `json:"duration_seconds,omitempty"`

	Topic string `json:"topic,omitempty"`

	TodoId int32 `json:"todo_id,omitempty"`

	CreatedAt string `json:"created_at,omitempty"`
}
