// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Pomo struct {
	ID              int64
	UserID          int64
	Status          string
	StartedAt       pgtype.Timestamptz
	EndedAt         pgtype.Timestamptz
	DurationSeconds pgtype.Int4
	IsPositive      bool
	Topic           pgtype.Text
	TodoID          pgtype.Int8
	Note            pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Todo struct {
	ID          int64
	Title       string
	Description pgtype.Text
	Status      string
	UserID      int64
	ParentID    pgtype.Int8
	SubTasks    []int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
